#!/bin/zsh

# this is quite broken right now, same with the firefox css
# (planning to fix both next time there's a decent holiday)
# everything in the spaces section and below is pretty much
# broken, my recommendation is to just scrap it

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo /opt/homebrew/bin/yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"

# IMPORTS

# import from pywal
. "${HOME}/.config/wal/argb.sh"

# CONSTANTS

# focus settings
yabai -m config mouse_follows_focus            off
yabai -m config focus_follows_mouse            autoraise

# window placement settings
yabai -m config auto_balance                   on
yabai -m config split_ratio                    0.5
yabai -m config window_topmost                 off
yabai -m config window_placement               second_child
yabai -m config window_origin_display          cursor

# window style settings
yabai -m config window_opacity_duration        0.0
yabai -m config active_window_opacity          1.0
yabai -m config normal_window_opacity          1.0
yabai -m config window_shadow                  off
yabai -m config window_opacity                 off

# border settings
yabai -m config window_border                  on
yabai -m config window_border_width            10

# colour settings
yabai -m config active_window_border_color     $color6
yabai -m config normal_window_border_color     $color6
yabai -m config insert_feedback_color          $color6

# modifier settings
yabai -m config mouse_modifier                 ctrl
yabai -m config mouse_action1                  resize
yabai -m config mouse_action2                  move
yabai -m config mouse_drop_action              swap

# window settings
yabai -m config layout                         bsp
yabai -m config top_padding                    5
yabai -m config bottom_padding                 20
yabai -m config left_padding                   20
yabai -m config right_padding                  20
yabai -m config window_gap                     25

# SPACES

# configure spaces
yabai -m space 1 --label main
yabai -m space 2 --label social
yabai -m space 3 --label browser
yabai -m space 4 --label code
yabai -m space 5 --label terminal
yabai -m space 6 --label media

## 1: organisation
#yabai -m rule --add app="Calendar"             space=1
#yabai -m rule --add app="Mail"                 space=1
#yabai -m rule --add app="Reminders"            space=1
#yabai -m rule --add app="Microsoft Outlook"    space=1#

## 2: social
#yabai -m rule --add app="Discord"              space=2
#yabai -m rule --add app="Messages"             space=2
#yabai -m rule --add app="Slack"                space=2#

## 3: browser
#yabai -m rule --add app="Firefox"              space=3
#yabai -m rule --add app="^.*Chrome$"           space=3#

## 4: main
#yabai -m rule --add app="^Code$"             space=4
#yabai -m rule --add app="^Microsoft [^O].*$"   space=4
#yabai -m rule --add app="Preview"              space=4#

## 5: terminal
#yabai -m rule --add app="Terminal"             space=5
#yabai -m rule --add app="iTerm2"               space=5#

## 6: media
#yabai -m rule --add app="QuickTime Player"     space=6
#yabai -m rule --add app="Spotify"              space=6
#yabai -m rule --add app="Music"                space=6

# APP SETTINGS

main_apps="(Calendar|Mail|Reminders|Microsoft\ Outlook|Discord|Messages|Slack|Firefox|Chrome|Code|Microsoft\ Word|Preview|Terminal|iTerm2|QuickTime|Player|Spotify|Music|DB Browser\ for\ SQLite)"

border_apps="(Finder|System\ Preferences|Notes)"

# general app settings
yabai -m rule --add app="^${border_apps}$"     border=on

# NOTE: these must come last, otherwise they'll mess with everything else for some reason
# send main apps to bottom layer (prevent covering dialogues)
yabai -m rule --add app="^${main_apps}$"       manage=on layer=below

# any apps that aren't main, day-to-day applications get put to float
yabai -m rule --add app!="^${main_apps}$"      manage=off

# and fuck vscode!
yabai -m rule --add app="^Code$"               border=off

echo "yabai configuration loaded.."

